steps:
  - script: |
      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      FULL_IMAGE="docker.io/$(dockerImageNamev1):$(fileHash)"

      echo "Scanning image: $FULL_IMAGE"
      ./bin/trivy image --severity HIGH,CRITICAL --format json -o trivy-results.json "$FULL_IMAGE"

      if [ -f trivy-results.json ]; then
        VULNS=$(jq '.Results[].Vulnerabilities | length' trivy-results.json | awk '{sum += $1} END {print sum}')
        echo "Found $VULNS vulnerabilities"

        if [ "$VULNS" -gt 0 ]; then
          echo "##vso[task.logissue type=error]Security vulnerabilities found: $VULNS"
          echo "##vso[task.setvariable variable=vulnsFound;isOutput=true]true"
        else
          echo "##vso[task.setvariable variable=vulnsFound;isOutput=true]false"
        fi
      else
        echo "##vso[task.logissue type=error]trivy-results.json not found or failed to generate"
      fi
    displayName: 'Scan Docker Image with Trivy (Remote)'

  - task: SendEmail@1
    condition: eq(variables['vulnsFound'], 'true')
    inputs:
      To: 'dev.fastcloud@gmail.com'
      Subject: '⚠️ Vulnerabilities found in Docker Image $(dockerImageNamev1):$(fileHash)'
      Body: 'Trivy found HIGH/CRITICAL vulnerabilities. Review build logs for details.'
    displayName: 'Notify Security Team via Email'
